### ISSUE TITLE
WebSocket Support

### ISSUE THREAD

**Issue by caleblloyd** [Cysharp/AlterNats#15]
Is WebSocket support something that you would be interested in for this repository?

I could contribute it, if you think it would be meaningful here.  I have it mostly done on a fork.

**Comment by neuecc** [comment]
If it does not increase complexity and does not affect the performance of existing TCP connections, it is a good.
However, I am not sure how meaningful that support would be for this library, which is limited to .NET 6.

**Comment by caleblloyd** [comment]
I opened a PR for it so you can see if it would be a good fit for this Library.  But if you would prefer to keep this version of the Library focused on TCP, I can also just keep it in the fork, and eventually publish a version of the fork to NuGet.

**Comment by neuecc** [comment]
I don't think Fork is a good idea, and I thought it was simple enough to isolate!
Thank you very much, I will release this.
