### ISSUE TITLE
in parameter in async method

### ISSUE THREAD

**Issue by scottf** [Cysharp/AlterNats#4]
[NatsReadProtocolProcessor line 224](https://github.com/Cysharp/AlterNats/blob/master/src/AlterNats/NatsReadProtocolProcessor.cs#L224)

I get an IDE (JetBrains Rider) error that says "Async method cannot have 'in' parameters"
```
async ValueTask<ReadOnlySequence<byte>> DispatchCommandAsync(int code, in ReadOnlySequence<byte> buffer)
```
.NET docs seem to say the same thing. https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/in-parameter-modifier

The code compiles and seems to run fine. Since it's an 'in' parameter and it's not modified there doesn't seem to be a problem. Not sure what the compiler does though.

**Comment by neuecc** [comment]
Thanks.
I've found the bug of compiler, if attached AsyncMethodBuilderAttribute, compiler pass invalid out/ref/in.
https://twitter.com/neuecc/status/1506262798946701314
For out and ref, it works incorrectly, but for in, it seems to work. 
However, it is not a good implementation.
Fixed.
