### ISSUE TITLE
Consider removing serialization from the library

### ISSUE THREAD

**Issue by israellot** [Cysharp/AlterNats#8]
This library currently is opinionated towards the use of serialized messages.
I believe serialization should be an outer layer on top of the library and not a concern of a core pubsub library. The api footprint could be smaller and other solutions would wrap around this implementation, in a more onion fashion.
I understand the concerns for performance, and for that I believe having the proper apis, exposing IBufferWritter for example would do the trick.
As an anecdotal, I have a use case where I have different serializers for different messages on a system published at the same bus, so I need to look at a particular signature at the topic to decide which serializer to use for each individual message. This is due to legacy systems having to co-exist with newer implementations on a transition phase.

**Comment by neuecc** [comment]
`byte[]`  or `ReadOnlyMemory<byte>` are treated specially and goes through serialization.
If you want to place it on an external layer, you can use byte[] and it will be handled just like any other library.
As I explained in Blog, it is difficult to have zero-copy and zero allocation if the serialization is not inside.
By making it a byte[], there will be copying and allocation, but it will be what you want.

**Comment by israellot** [comment]
Thanks @neuecc ! I've read the blog and understood your chain of thought.
