### ISSUE TITLE
Performance question

### ISSUE THREAD

**Issue by 80dB** [Cysharp/AlterNats#9]
Full disclosure, I wrote my own Nats client a while back. But was wondering how AlterNats would perform vs my own implementation.  

So I tried a simple example when looking at the performance of AlterNats and was wondering what I'm doing wrong here:
```csharp
using AlterNats;
using System.Diagnostics;

namespace SimpleTest;

class Program
{
    static async Task Main(string[] args)
    {

        var cancellation = new CancellationTokenSource();
        
        var reader = Task.Run(() => ReaderText(cancellation.Token), CancellationToken.None);
        var writer = Task.Run(() => WriterText(cancellation.Token), CancellationToken.None);


        Console.ReadKey();

        cancellation.Cancel();

        try
        {
            await reader;
        }
        catch 
        {
            // Don't care
        }

        try
        {
            await writer;
        }
        catch
        {
            // Don't care
        }
    }

    static async Task WriterText(CancellationToken cancellationToken)
    {
        await using var conn = new NatsConnection();
        var key = new NatsKey("HELLO");
        while (!cancellationToken.IsCancellationRequested)
        {
            await conn.PublishAsync(key, "HELLO WORLD");
        }
    }

    static async Task ReaderText(CancellationToken cancellationToken)
    {
        await using var conn = new NatsConnection();
        var history = new Queue<(int count, long time)>();
        var counter = 0;
        var prev = 0;
        var watch = Stopwatch.StartNew();

        using var subscription = await conn.SubscribeAsync<string>("HELLO", text =>
        {
            counter++;
            if (counter % 100_000 != 0) return;
            watch.Stop();
            history.Enqueue((counter - prev, watch.ElapsedMilliseconds));
            prev = counter;
            if (history.Count > 10) history.Dequeue();

            var count = history.Sum(h => h.count);
            var time = history.Sum(h => h.time);

            Console.WriteLine($"{text} - {count / (double)time * 1000}");
            watch = Stopwatch.StartNew();
        });

        await Task.Delay(TimeSpan.FromHours(1), cancellationToken);
    }
}
```

On my computer this gets around 28k messages per second [release build]. This makes me wonder what I'm doing wrong. It helped when I made the reader use a different connection from the writer, but not a significant performance bump.

I'm guessing publishing a batch would be faster, but that does require the sender to be more complex (as it will need to add support for batching). 

Note the above example gets around 665k messages per second using my AsyncNats [ https://github.com/80dB/AsyncNats ] , which makes me wonder if I'm doing something wrong. As some of the idea's in your implementation are much nicer.

**Comment by israellot** [comment]
Maybe try using **PostPublish** instead of **PublishAsync**
I guess that would align better with the behavior you had in mind. 
**PublishAsync** will await on network.

**Comment by 80dB** [comment]
After changing from PublishAsync to PostPublish, the performance was nearly identical. Except PostPublish doesn't seem to have any buffer limiting?

**Comment by israellot** [comment]
I've ran your example @80dB.
With this loop I get around 30k/s as you mentioned
```
while (!cancellationToken.IsCancellationRequested)
     await conn.PublishAsync(key, "HELLO WORLD");
```
With this one I get >1M/s
```
while (!cancellationToken.IsCancellationRequested)
     conn.PostPublish(key, "HELLO WORLD");
```

So I wonder what might be happening on your end.
I used a console app on dotnet 6, Release build.

**Comment by neuecc** [comment]
Ssingle request, PublishAsync each time, would greatly affect the benchmark because no automatic pipelining would be used at all.
For practical purposes, I believe that pipelining will work depending on the number of simultaneous accesses at the time, etc., since the web server handles multiple requests at the same time.

All messages are retained by UnboundedChannel.
https://github.com/Cysharp/AlterNats/blob/a575eae/src/AlterNats/NatsConnection.cs#L32
However, the network buffer itself is limited by NatsOptions.WriterBufferSize.
https://github.com/Cysharp/AlterNats/blob/master/src/AlterNats/NatsPipeliningWriteProtocolProcessor.cs#L113
I am not considering whether to set a limit on the number of messages.

**Comment by 80dB** [comment]
@israellot as I mentioned, PostPublish does get me equal performance (1M/s is impressive, I was getting around 720k-750k/s running on Windows with a 12900k CPU), but have you checked memory usage while running with PostPublish?  It rapidly increases to a point where it just OOM's .

**Comment by neuecc** [comment]
It seems easy to change the behavior to make them wait if overflow by using BoundedChannel and add PostPublishAsync method, I'll think about that.

**Comment by israellot** [comment]
> @israellot as I mentioned, PostPublish does get me equal performance (1M/s is impressive, I was getting around 720k-750k/s running on Windows with a 12900k CPU), but have you checked memory usage while running with PostPublish? It rapidly increases to a point where it just OOM's .

Sorry, I misread your reply. You are correct, memory does skyrocket.

**Comment by neuecc** [comment]
blogged about cancellation and performance
https://neuecc.medium.com/patterns-practices-for-efficiently-handling-c-async-await-cancel-processing-and-timeouts-b419ce5f69a4
